import os
import shutil
from pathlib import Path
import click
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from macclean.core.utils import CleanItem, AnalysisResult, format_size, confirm, dir_size

console = Console()

_ARTIFACT_DIRS = {
    "node_modules": "Node.js dependencies",
    ".venv": "Python virtualenv",
    "venv": "Python virtualenv",
    "env": "Python virtualenv",
    "__pycache__": "Python cache",
    "build": "Build output",
    "dist": "Distribution output",
    "target": "Rust/Java build output",
    ".next": "Next.js build cache",
    ".nuxt": "Nuxt.js build cache",
    ".parcel-cache": "Parcel cache",
    ".turbo": "Turborepo cache",
}

_SKIP_ROOTS = {".git", ".ssh", "Library", "Applications", ".Trash"}


def _scan_projects(root: Path, max_depth: int = 5) -> list[tuple[str, Path, int]]:
    results = []
    try:
        for dirpath, dirs, _ in os.walk(str(root), followlinks=False):
            depth = dirpath.count(os.sep) - str(root).count(os.sep)
            if depth > max_depth:
                dirs.clear()
                continue
            dirs[:] = [
                d for d in dirs
                if d not in _SKIP_ROOTS
                and (not d.startswith(".") or d in _ARTIFACT_DIRS)
            ]
            for dirname in list(dirs):
                if dirname in _ARTIFACT_DIRS:
                    artifact_path = Path(dirpath) / dirname
                    size = dir_size(artifact_path)
                    if size > 0:
                        results.append((_ARTIFACT_DIRS[dirname], artifact_path, size))
                    dirs.remove(dirname)
    except (PermissionError, OSError):
        pass
    return results


def analyze(home: Path | None = None) -> AnalysisResult:
    home = home or Path.home()
    result = AnalysisResult()
    for label, path, size in _scan_projects(root=home):
        result.items.append(CleanItem(
            label=f"{label} — {str(path).replace(str(home), '~')}",
            path=path, size_bytes=size,
        ))
    return result


def clean(result: AnalysisResult, dry_run: bool = False, yes: bool = False) -> None:
    if not result.items:
        console.print("[green]No project artifacts found.[/]")
        return

    sorted_items = sorted(result.items, key=lambda x: x.size_bytes, reverse=True)

    table = Table(show_header=True, show_lines=True)
    table.add_column("Type & Path")
    table.add_column("Size", justify="right")
    for item in sorted_items[:40]:
        color = "red" if item.size_bytes > 500*1024**2 else "yellow" if item.size_bytes > 50*1024**2 else "white"
        table.add_row(item.label, f"[{color}]{format_size(item.size_bytes)}[/{color}]")
    if len(sorted_items) > 40:
        table.add_row(f"[dim]... and {len(sorted_items)-40} more[/]", "")

    console.print(Panel(table, title="[bold cyan]Project Artifacts[/]"))
    console.print(f"  {len(result.items)} directories · Total recoverable: [bold]{format_size(result.total_bytes)}[/]")
    console.print("  [dim]These are regenerated by npm install / pip install / build.[/]")

    if dry_run:
        return
    if not yes and not confirm(f"Delete all {len(result.items)} artifact directories?"):
        return

    for item in result.items:
        try:
            shutil.rmtree(item.path, ignore_errors=True)
            console.print(f"  [green]+[/] {item.label}")
        except Exception as e:
            console.print(f"  [yellow]![/] {item.label}: {e}")


@click.command()
@click.option("--path", "scan_path", default=None, help="Root to scan (default: home)")
@click.pass_context
def cmd(ctx, scan_path: str | None):
    """Find and remove project build artifacts (node_modules, .venv, build/, etc.)."""
    root = Path(scan_path) if scan_path else Path.home()
    console.print(f"[dim]Scanning {root} for project artifacts...[/]")
    result = analyze(home=root)
    clean(result, dry_run=ctx.obj["dry_run"], yes=ctx.obj["yes"])
